# Generated by Django 3.2.8 on 2021-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
