# Generated by Django 3.2.8 on 2021-10-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesAPI', '0002_alter_quote_quote_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=155),
        ),
    ]
